##################################################
### Install packages
- name: Install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-pptp-gnome
    - network-manager-vpnc
    - network-manager-vpnc-gnome
    - network-manager-openconnect
    - network-manager-openconnect-gnome