##################################################
### Check installed packages
- name: Check installed packages
  become: true
  shell: 'apt-cache search dbeaver | wc -l'
  register: package_found

##################################################
### Download packages
- name: Download packages
  get_url:
    url: "{{ dbeaver_url }}/{{ dbeaver_package }}"
    dest: "/tmp/{{ dbeaver_package }}"
  when: package_found.stdout != "1"

##################################################
### Install packages
- name: Install packages
  become: true
  apt: deb={{ item }}
  with_items:
   - "/tmp/{{ dbeaver_package }}"
  when: package_found.stdout != "1"
