##################################################
### Pre-checks
- name: Check installed vagrant version
  shell: 'dpkg --list | grep vagrant | grep "^ii" | wc -l'
  register: vagrant_installed

- name: Check if required vagrant version is installed
  shell: 'dpkg --list | grep vagrant | grep {{ vagrant_version }} | grep "^ii" | wc -l'
  register: vagrant_required_installed

- name: Remove different vagrant version if installed
  become: true
  apt: name=vagrant state=absent purge=yes autoremove=yes
  when: vagrant_installed.stdout != "0" and vagrant_required_installed.stdout == "0"

##################################################
### Download packages
- name: Download packages
  get_url:
    url: "{{ vagrant_url }}/{{ vagrant_package }}"
    dest: "/tmp/{{ vagrant_package }}"
  when: vagrant_required_installed.stdout == "0"

##################################################
### Install packages
- name: Install packages
  become: true
  apt: deb={{ item }}
  with_items:
   - "/tmp/{{ vagrant_package }}"
  when: vagrant_required_installed.stdout == "0"

##################################################
### Prepare Folder Structure
- name: Create Folder Structure
  file: path={{ item.path }} mode={{ item.mode }} state=directory
  with_items:
   - { path: "~/vagrant", mode: 755 }
