##################################################
### Install packages
- name: Add apt key
  become: true
  apt_key: url={{ item }} state=present
  with_items:
    - "{{ vscode_repository_key }}"

- name: Add repository
  become: true
  apt_repository: repo="deb [arch=amd64] {{ vscode_repository }} stable main" state=present update_cache=yes

- name: Install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - code
