##################################################
### Install packages
- name: Install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - git-core
    - zsh
    - fonts-powerline

- name: Check if zsh is already installed
  shell: dpkg -l | grep "^ii  zsh" | wc -l
  register: zsh_installed

- name: Download zsh installer
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh_installer.sh
    mode: 0777
  when: zsh_installed.stdout != "0"

- name: Install oh my zsh
  shell: bash zsh_installer.sh
  args:
    chdir: /tmp/
  ignore_errors: yes # TODO: Fix "Password: chsh: PAM: Authentication failure"
  when: zsh_installed.stdout != "0"

- name: Choose theme agnoster
  lineinfile:
    dest: ~/.zshrc
    regexp: 'ZSH_THEME="robbyrussell"'
    line: 'ZSH_THEME="agnoster"'
    backrefs: yes

- name: Replace user bash with zsh
  shell: whoami
  register: user

- name: Set zsh as default shell
  become: true
  user: name={{ user.stdout }} shell=/bin/zsh