##################################################
### Install packages
- name: Add repository
  become: true
  apt_repository: repo="deb {{ opera_repository }} stable non-free" state=present update_cache=yes

- name: Install packages
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - opera-stable
