##################################################
### Install packages
- name: Add repository
  become: true
  apt_repository: repo="{{ seafile_ppa }}" state=present update_cache=yes

- name: Install packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - seafile-gui

##################################################
### Prepare Folder Structure
- name: Create Folder Structure
  file: path={{ item.path }} mode={{ item.mode }} state=directory
  with_items:
   - { path: "~/seafile", mode: 755 }
