##################################################
### Check installed packages
- name: Check installed packages
  become: true
  stat: path=/opt/cisco/vpn/
  register: anyconnect_installed

##################################################
### Download packages
- name: Download packages
  get_url:
    url: "{{ anyconnect_url }}"
    dest: "/tmp/{{ anyconnect_package }}"
  when: anyconnect_installed.stat.isdir is not defined

- name: Extract packages
  unarchive: src="/tmp/{{ anyconnect_package }}" dest="/tmp/"
  when: anyconnect_installed.stat.isdir is not defined

##################################################
### Install packages
- name: Install packages
  become: true
  shell: "cd /tmp/anyconnect*/vpn/ && rm license.txt && ./vpn_install.sh"
  when: anyconnect_installed.stat.isdir is not defined
