##################################################
### Check installed packages
- name: Check installed packages
  become: true
  shell: 'apt-cache search gnome-connection-manager | wc -l'
  register: package_found

##################################################
### Download packages
- name: Download packages
  get_url:
    url: "{{ gcm_url }}/{{ gcm_package }}"
    dest: "/tmp/{{ gcm_package }}"
  when: package_found.stdout != "1"

##################################################
### Install packages
- name: Install packages
  become: true
  apt: deb={{ item }}
  with_items:
   - "/tmp/{{ gcm_package }}"
  when: package_found.stdout != "1"

##################################################
### Configuration
- name: Configure user home as default Path
  become: true
  template: src={{ item.src }} dest={{ item.dest }} mode=755
  with_items:
    - { src: gnome-connection-manager, dest: /usr/bin/gnome-connection-manager }
