##################################################
### Install office tools
- name: Install office tools
  become: true
  apt: name={{ item }} state=present
  with_items:
    - thunderbird
    - shutter
    - keepassx